-- :options  // gives all config options
-- so % // loads script
require("libs.plugins")
require("libs.mason")
require("libs.set")
require("libs.tree-sitter")
require("libs.lsps")
require("libs.remaps")
require("libs.autocmd")
require("libs.spell")
require("libs.lint")
require("libs.windows")
require("libs.copilot")
require("libs.vim-test")
require("libs.harpoon")
require("libs.oil")
