-- :options  // gives all config options
-- so % // loads script
require("libs.plugins")
require("libs.neo-dev")
require("libs.mason")
require("libs.options")
require("libs.tree-sitter")
require("libs.lsps.init")
require("libs.remaps")
require("libs.autocmd")
require("libs.none-ls")
require("libs.mason-tool-installer-nvim")
require("libs.windows")
require("libs.copilot")
require("libs.vim-test.init")
require("libs.harpoon")
require("libs.oil")
require("libs.vim-fugitive")
require("libs.dap.init")
require("libs.diagnostic")
require("libs.telescope")
require("libs.noice")
require("libs.theme")
require("libs.status-line")
require("libs.nerd-commenter")
require("libs.trouble-nvim")
